### ISSUE TITLE
Extract translation

### ISSUE THREAD

**Issue by heldersilvaoliveira** [Cocolabs-SAS/cocorico#239]
| Q                | A
| ---------------- | -----
| Bug report?      | [  ]
| Feature request? | [  ]
| Support request? | [ X]

Hi, I'm having some trouble adding a new language.
I updated Cocorico/CoreBundle/Resources/config/parameters.yml having now the following
```
    locale: en

    cocorico.locale: en
    cocorico.locales:
            - en
            - it
    cocorico.locales_string: en|it
```

and ran _php app/console translation:extract it --config=cocorico_ with the following outcome:

```
The program 'php' can be found in the following packages:
* php7.0-cli
* hhvm
Try: apt install <select package>
```

Any clue on how to install the language?
Thank you
